"use client";

import { useEffect, useState } from "react";
import { getTickets, updateTicket } from "@/lib/api";
import type { Ticket } from "@/lib/types";

export default function TicketsPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [filter, setFilter] = useState("all");
  const [selected, setSelected] = useState<Ticket | null>(null);

  useEffect(() => { loadTickets(); }, []);

  async function loadTickets() {
    try { setTickets(await getTickets({ limit: 100 })); } catch {}
  }

  async function handleStatusChange(id: number, status: string) {
    try {
      await updateTicket(id, { status });
      loadTickets();
      if (selected?.id === id) setSelected({ ...selected, status });
    } catch {}
  }

  const filtered = filter === "all" ? tickets :
    filter === "security" ? tickets.filter(t => t.category === "security_incident") :
    filter === "it" ? tickets.filter(t => t.category !== "security_incident") :
    tickets.filter(t => t.status === filter);

  const categoryIcons: Record<string, string> = {
    security_incident: "🔴", vpn: "🌐", email: "📧", printer: "🖨️",
    performance: "⚡", account: "🔑", software: "💾", other: "📋",
  };

  return (
    <div className="sf-animate-in">
      <div className="sf-page-header">
        <div>
          <h1 className="sf-page-title">🎫 Ticket Management</h1>
          <p className="sf-page-subtitle">{tickets.length} total tickets • Auto-generated by AI agents</p>
        </div>
        <div style={{ display: "flex", gap: "8px" }}>
          {["all", "open", "security", "it"].map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={`sf-btn sf-btn-sm ${filter === f ? "sf-btn-primary" : "sf-btn-secondary"}`}>
              {f === "all" ? "All" : f === "open" ? "Open" : f === "security" ? "🔒 Security" : "🔧 IT Support"}
            </button>
          ))}
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: selected ? "1fr 1fr" : "1fr", gap: "20px" }}>
        {/* Ticket List */}
        <div className="sf-card" style={{ overflow: "auto", maxHeight: "calc(100vh - 160px)" }}>
          {filtered.length === 0 ? (
            <div style={{ textAlign: "center", padding: "60px", color: "var(--sf-text-muted)" }}>
              <div style={{ fontSize: "48px", marginBottom: "16px" }}>🎫</div>
              <div style={{ fontSize: "16px", fontWeight: 600 }}>No tickets found</div>
              <div style={{ fontSize: "13px", marginTop: "8px" }}>Tickets are auto-created by AI agents during analysis</div>
            </div>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              {filtered.map(t => (
                <div key={t.id} onClick={() => setSelected(t)}
                  style={{
                    padding: "16px", borderRadius: "10px", cursor: "pointer",
                    background: selected?.id === t.id ? "rgba(99,102,241,0.08)" : "rgba(255,255,255,0.02)",
                    border: `1px solid ${selected?.id === t.id ? "rgba(99,102,241,0.3)" : "var(--sf-border)"}`,
                    transition: "all 0.2s ease",
                  }}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "8px" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span>{categoryIcons[t.category] || "📋"}</span>
                      <span style={{ fontSize: "14px", fontWeight: 600, color: "var(--sf-text-primary)" }}>#{t.id} {t.title}</span>
                    </div>
                    <span className={`sf-badge ${t.priority.toLowerCase()}`}>{t.priority}</span>
                  </div>
                  <div style={{ display: "flex", gap: "8px" }}>
                    <span className={`sf-badge ${t.status.replace("_", "")}`}>{t.status.replace("_", " ")}</span>
                    <span style={{ fontSize: "11px", color: "var(--sf-text-muted)", textTransform: "capitalize" }}>
                      {t.category.replace(/_/g, " ")}
                    </span>
                    <span style={{ fontSize: "11px", color: "var(--sf-text-muted)" }}>
                      via {t.source.replace("_", " ")}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Ticket Detail */}
        {selected && (
          <div className="sf-card sf-animate-in" style={{ overflow: "auto", maxHeight: "calc(100vh - 160px)" }}>
            <div style={{ marginBottom: "20px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" }}>
                <span style={{ fontSize: "24px" }}>{categoryIcons[selected.category] || "📋"}</span>
                <h2 style={{ fontSize: "18px", fontWeight: 700 }}>#{selected.id} {selected.title}</h2>
              </div>
              <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "16px" }}>
                <span className={`sf-badge ${selected.priority.toLowerCase()}`}>{selected.priority}</span>
                <span className={`sf-badge ${selected.status}`}>{selected.status.replace("_", " ")}</span>
                <span className={`sf-badge info`}>{selected.category.replace(/_/g, " ")}</span>
              </div>
            </div>

            {selected.description && (
              <div style={{ marginBottom: "16px" }}>
                <div style={{ fontSize: "12px", fontWeight: 700, color: "var(--sf-text-muted)", marginBottom: "6px" }}>Description</div>
                <div style={{ fontSize: "13px", color: "var(--sf-text-secondary)", lineHeight: 1.6 }}>{selected.description}</div>
              </div>
            )}

            {selected.diagnosis && (
              <div style={{ padding: "14px", borderRadius: "10px", background: "rgba(99,102,241,0.05)", border: "1px solid rgba(99,102,241,0.15)", marginBottom: "16px" }}>
                <div style={{ fontSize: "12px", fontWeight: 700, color: "var(--sf-accent-light)", marginBottom: "6px" }}>🤖 AI Diagnosis</div>
                <div className="sf-markdown" style={{ fontSize: "13px", color: "var(--sf-text-secondary)", lineHeight: 1.6, whiteSpace: "pre-wrap" }}>
                  {selected.diagnosis}
                </div>
              </div>
            )}

            {/* Timeline */}
            {selected.timeline && selected.timeline.length > 0 && (
              <div style={{ marginBottom: "16px" }}>
                <div style={{ fontSize: "12px", fontWeight: 700, color: "var(--sf-text-muted)", marginBottom: "8px" }}>Timeline</div>
                {selected.timeline.map((entry: any, i: number) => (
                  <div key={i} style={{
                    display: "flex", gap: "12px", padding: "8px 0",
                    borderLeft: "2px solid var(--sf-border)", paddingLeft: "16px", marginLeft: "8px",
                  }}>
                    <div>
                      <div style={{ fontSize: "12px", color: "var(--sf-text-muted)" }}>
                        {entry.timestamp ? new Date(entry.timestamp).toLocaleString() : "N/A"}
                      </div>
                      <div style={{ fontSize: "13px", color: "var(--sf-text-secondary)" }}>{entry.action}</div>
                      <div style={{ fontSize: "11px", color: "var(--sf-text-muted)" }}>by {entry.actor}</div>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Actions */}
            <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
              <button className="sf-btn sf-btn-success sf-btn-sm" onClick={() => handleStatusChange(selected.id, "resolved")}>✓ Resolve</button>
              <button className="sf-btn sf-btn-warning sf-btn-sm" style={{ background: "rgba(245,158,11,0.15)", color: "#fde047", border: "1px solid rgba(245,158,11,0.3)" }} onClick={() => handleStatusChange(selected.id, "escalated")}>⬆ Escalate</button>
              <button className="sf-btn sf-btn-secondary sf-btn-sm" onClick={() => handleStatusChange(selected.id, "in_progress")}>▶ In Progress</button>
              <button className="sf-btn sf-btn-secondary sf-btn-sm" onClick={() => handleStatusChange(selected.id, "closed")}>✕ Close</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
